version: "3.7"
services: 
  nginx:
    restart: always
    build: ./nginx
    ports:
        - 80:80
        - 8080:8080
    depends_on:
      - api
      - client

  api:
    build: ./api
    restart: on-failure
    volumes:
        - ./api:/app
        - /app/vendor
    environment:
        - ENV=LOCAL
        - DBHOST=db
        - DBPORT=3306
        - DATABASE=database
    links:
        - db

  client:
    build: ./client
    restart: on-failure
    volumes:
        - ./client:/app
        - /app/node_modules

  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=database
    ports:
     - "3306:3306"
